# rosvoice
#普通文本
这是一段普通的文本
##关于换行
直接回车不能换行，<br>
可以使用\<br>。
但是使用html标签就丧失了markdown的意义。  
可以在上一行文本后面补两个空格，  
这样下一行的文本就换行了。

或者就是在两行文本直接加一个空行。

也能实现换行效果，不过这个行间距有点大。
#单行文本
    Hello,大家好，我是rosvoice。
#文本块
    欢迎到访
    很高兴见到您
    祝您，早上好，中午好，下午好，晚安
